# Generated by Django 5.2.9 on 2025-12-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('master', '0004_productionparameter_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('plan', models.PositiveIntegerField()),
                ('actual', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(unique=True)),
                ('target_output', models.PositiveIntegerField()),
                ('worktime_output', models.PositiveIntegerField()),
                ('actual_output', models.PositiveIntegerField()),
                ('reject_output', models.PositiveIntegerField()),
                ('downtime_output', models.FloatField(help_text='Downtime in hours')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved')], default='open', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.problemcategory')),
                ('prod_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prodoperation')),
            ],
        ),
        migrations.CreateModel(
            name='ProdReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reject_photo', models.ImageField(blank=True, null=True, upload_to='reject_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prodoperation')),
                ('reject_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.rejectcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shoots', models.PositiveIntegerField()),
                ('preheat', models.PositiveIntegerField()),
                ('target_pcs', models.PositiveIntegerField()),
                ('work_time', models.FloatField(help_text='Work time in hours')),
                ('actual_total', models.PositiveIntegerField()),
                ('reject_total', models.PositiveIntegerField()),
                ('downtime_total', models.FloatField(help_text='Downtime in hours')),
                ('status_process', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('mode_status', models.CharField(choices=[('normal', 'Normal'), ('overtime', 'Overtime'), ('dandory', 'Dandory')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.operator')),
                ('prod_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.productionparameter')),
            ],
        ),
        migrations.AddField(
            model_name='prodoperation',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.production'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('shift', models.PositiveSmallIntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2'), (3, 'Shift 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.dailyproduction')),
            ],
            options={
                'ordering': ['scheduled_time', 'shift'],
                'unique_together': {('scheduled_time', 'shift')},
            },
        ),
        migrations.AddField(
            model_name='production',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schedule'),
        ),
    ]
