# Generated by Django 5.2.9 on 2025-12-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line_address', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('part_name', models.CharField(max_length=150)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavity', models.PositiveIntegerField()),
                ('runner', models.FloatField(help_text='Runner weight (kg)')),
                ('shot_weight', models.FloatField(help_text='Shot weight (kg)')),
                ('ascast', models.FloatField(help_text='As-cast weight (kg)')),
                ('cycle_time', models.FloatField(blank=True, help_text='Cycle time (seconds)', null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.part')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.machine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.part')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.shift')),
            ],
        ),
    ]
