# Generated by Django 5.2.9 on 2025-12-27 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sample_photo', models.ImageField(blank=True, null=True, upload_to='rejects/')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productionparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productionparameter',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.part'),
        ),
        migrations.CreateModel(
            name='ProductionCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_kg', models.FloatField(help_text='Normal production capacity (kg/hour)')),
                ('overtime_kg', models.FloatField(help_text='Overtime production capacity (kg/hour)')),
                ('dandory_kg', models.FloatField(help_text='Dandory production capacity (kg/hour)')),
                ('one_hour_pcs', models.PositiveIntegerField(help_text='One hour production capacity (pieces/hour)')),
                ('six_hour_pcs', models.PositiveIntegerField(help_text='Six hour production capacity (pieces/6 hours)')),
                ('seven_hour_pcs', models.PositiveIntegerField(help_text='Seven hour production capacity (pieces/7 hours)')),
                ('eight_hour_pcs', models.PositiveIntegerField(help_text='Eight hour production capacity (pieces/8 hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.productionparameter')),
            ],
        ),
    ]
