# Generated by Django 5.2.9 on 2025-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_problemcategory_rejectcategory_part_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionparameter',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
